const categories = {
    cars: [
        {
            id: Math.random(),
            userId: 1,
            paths: ['/images/cars/1/1.jpg', '/images/cars/1/2.jpg', '/images/cars/1/3.jpg'],
            description: 'Хороший товар',
            category: 'cars',
            product: 'Genesis G80',
            transmission: 'automatic',
            type: 'Седан',
            year: 2001,
            money: 3465000,
            date: new Date('2022-03-24'),
            selected: false,
            countViews: 555,
            address: 'Москва, улица Новый Арбат, дом 24'
        },
        {
            id: Math.random(),
            userId: 1,
            paths: ['/images/cars/2/1.jpg', '/images/cars/2/2.jpg', '/images/cars/2/3.jpg'],
            description: 'Хороший товар',
            category: 'cars',
            product: 'Volkswagen ID.4',
            transmission: 'automatic',
            type: 'Универсал',
            year: 2021,
            money: 4268000,
            date: new Date('2022-03-25'),
            selected: false,
            countViews: 10,
            address: 'Санкт-Петербург, улица Большая Конюшенная, дом 35'
        },
        {
            id: Math.random(),
            userId: 1,
            paths: ['/images/cars/3/1.jpg', '/images/cars/3/2.jpg', '/images/cars/3/3.jpg'],
            description: 'Хороший товар',
            category: 'cars',
            product: 'Peugeot 308 sw 2011',
            transmission: 'automatic',
            type: 'Хэтчбэк',
            year: 2022,
            money: 892000,
            date: new Date('2022-03-23'),
            selected: false,
            countViews: 20,
            address: 'Москва, улица Новый Арбат, дом 24'
        },
        {
            id: Math.random(),
            userId: 1,
            paths: ['/images/cars/4/1.jpg', '/images/cars/4/2.jpg', '/images/cars/4/3.jpg'],
            description: 'Хороший товар',
            category: 'cars',
            product: 'ВАЗ-2107 «Жигули» (LADA 2107)',
            transmission: 'manual',
            type: 'Седан',
            year: 1995,
            money: 130000,
            date: new Date('2022-03-20'),
            selected: false,
            countViews: 3,
            address: 'Санкт-Петербург, улица Большая Конюшенная, дом 35'
        },
        {
            id: Math.random(),
            userId: 1,
            paths: ['/images/cars/5/1.jpg', '/images/cars/5/2.jpg', '/images/cars/5/3.jpg'],
            description: 'Хороший товар',
            category: 'cars',
            product: 'Rhino GX Executive',
            transmission: 'manual',
            type: 'Внедорожник',
            year: 2022,
            money: 25000000,
            date: new Date('2022-03-25'),
            selected: false,
            countViews: 3,
            address: 'Санкт-Петербург, ул.Большая Конюшенная'
        },
    ],
    buildings: [
        {
            id: Math.random(),
            userId: 1,
            paths: ['/images/buildings/1/1.jpg', '/images/buildings/1/2.jpg', '/images/buildings/1/3.jpg'],
            description: 'Хороший товар',
            category: 'buildings',
            product: '4-к. квартира, 121 м², 9/17 эт.',
            room: 4,
            square: 121,
            type: 'Квартира',
            money: 16777300,
            date: new Date('2022-03-25'),
            selected: false,
            countViews: 5,
            address: 'Санкт-Петербург, ул.Большая Конюшенная'
        },
        {
            id: Math.random(),
            userId: 1,
            paths: ['/images/buildings/2/1.jpg', '/images/buildings/2/2.jpg', '/images/buildings/2/3.jpg'],
            description: 'Хороший товар',
            category: 'buildings',
            product: '1-к. квартира, 38 м², 11/17 эт.',
            room: 1,
            square: 38,
            type: 'Квартира',
            money: 3800000,
            date: new Date('2022-03-25'),
            selected: false,
            countViews: 3,
            address: 'Санкт-Петербург, улица Большая Конюшенная, дом 35'
        },
        {
            id: Math.random(),
            userId: 1,
            paths: ['/images/buildings/3/1.jpg', '/images/buildings/3/2.png', '/images/buildings/3/3.jpg'],
            description: 'Хороший товар',
            category: 'buildings',
            product: '2-к. апартаменты, 60 м², 10/11 эт.',
            room: 2,
            square: 60,
            type: 'Апартаменты',
            money: 5200000,
            date: new Date('2022-03-25'),
            selected: false,
            countViews: 3,
            address: 'Санкт-Петербург, ул.Большая Конюшенная'
        },
        {
            id: Math.random(),
            userId: 1,
            paths: ['/images/buildings/4/1.jpg', '/images/buildings/4/2.jpg', '/images/buildings/4/3.jpg'],
            description: 'Хороший товар',
            category: 'buildings',
            product: 'Дом 76 м² на участке 4 сот.',
            room: 3,
            square: 76,
            type: 'Дом',
            money: 5500000,
            date: new Date('2022-03-25'),
            selected: false,
            countViews: 3,
            address: 'Санкт-Петербург, ул.Большая Конюшенная'
        },
        {
            id: Math.random(),
            userId: 1,
            paths: ['/images/buildings/5/1.jpg', '/images/buildings/5/2.png', '/images/buildings/5/3.jpg'],
            description: 'Хороший товар',
            category: 'buildings',
            product: 'Квартира-студия, 20 м², 17/18 эт.',
            room: 1,
            type: 'Квартира',
            square: 20,
            money: 2450000,
            countViews: 3,
            date: new Date('2022-03-25'),
            selected: false,
            address: 'Санкт-Петербург, ул.Большая Конюшенная'
        },
    ],
    cameras: [
        {
            id: Math.random(),
            userId: 1,
            paths: ['/images/cameras/1/1.jpg', '/images/cameras/1/2.jpg', '/images/cameras/1/3.jpg'],
            description: 'Хороший товар',
            category: 'cameras',
            product: 'Canon EOS R6 Kit',
            type: 'Цифровой',
            matrix: 20,
            video: '3840x2160',
            money: 319990,
            countViews: 3,
            date: new Date('2022-03-25'),
            selected: false,
            address: 'Санкт-Петербург, ул.Большая Конюшенная'
        },
        {
            id: Math.random(),
            userId: 1,
            paths: ['/images/cameras/2/1.jpg', '/images/cameras/2/2.jpg', '/images/cameras/2/3.jpg'],
            description: 'Хороший товар',
            category: 'cameras',
            type: 'Цифровой',
            matrix: 15,
            video: '3840x2160',
            product: 'Sony Cyber-shot DSC-RX0 II G',
            money: 50990,
            date: new Date('2022-03-25'),
            selected: false,
            countViews: 3,
            address: 'Санкт-Петербург, ул.Большая Конюшенная'
        },
        {
            id: Math.random(),
            userId: 1,
            paths: ['/images/cameras/3/1.jpg', '/images/cameras/3/2.jpg', '/images/cameras/3/3.jpg'],
            description: 'Хороший товар',
            category: 'cameras',
            type: 'Беззеркальный',
            matrix: 25,
            video: '3840x2160',
            product: 'Sony Alpha A6100',
            money: 105000,
            date: new Date('2022-03-25'),
            selected: false,
            countViews: 3,
            address: 'Санкт-Петербург, ул.Большая Конюшенная'
        },
        {
            id: Math.random(),
            userId: 1,
            paths: ['/images/cameras/4/1.jpg', '/images/cameras/4/2.jpg', '/images/cameras/4/3.jpg'],
            description: 'Хороший товар',
            category: 'cameras',
            product: 'Nikon D3300 Kit',
            type: 'Зеркальный',
            matrix: 24,
            video: '1920x1080',
            money: 26800,
            date: new Date('2022-03-25'),
            selected: false,
            countViews: 3,
            address: 'Санкт-Петербург, ул.Большая Конюшенная'
        },
        {
            id: Math.random(),
            userId: 1,
            paths: ['/images/cameras/5/1.jpg', '/images/cameras/5/2.jpg', '/images/cameras/5/3.jpg'],
            description: 'Хороший товар',
            category: 'cameras',
            type: 'Беззеркальный',
            matrix: 47,
            video: '3840x2160',
            product: 'Leica SL2 Kit 24-70 f/2.8',
            money: 677493,
            date: new Date('2022-03-25'),
            selected: false,
            countViews: 3,
            address: 'Санкт-Петербург, ул.Большая Конюшенная'
        },
    ],
    notebooks: [
        {
            id: Math.random(),
            userId: 1,
            paths: ['/images/notebooks/1/1.jpg', '/images/notebooks/1/2.jpg', '/images/notebooks/1/3.jpg'],
            description: 'Хороший товар',
            category: 'notebooks',
            product: 'Ноутбук HUAWEI MateBook D 17 HVY-WAP9',
            type: 'Домашний ноутбук',
            screenSize: 17,
            processor: 'Intel Core i7',
            ram: 16,
            money: 79999,
            date: new Date('2022-03-25'),
            selected: false,
            countViews: 3,
            address: 'Санкт-Петербург, ул.Большая Конюшенная'
        },
        {
            id: Math.random(),
            userId: 1,
            paths: ['/images/notebooks/2/1.jpg', '/images/notebooks/2/2.jpg', '/images/notebooks/2/3.jpg'],
            description: 'Хороший товар',
            category: 'notebooks',
            product: 'Ноутбук MSI Sword 15 A12UE-286XRU белый',
            screenSize: 15,
            processor: 'Intel Core i5',
            ram: 8,
            type: 'Домашний ноутбук',
            money: 114999,
            date: new Date('2022-03-25'),
            selected: false,
            countViews: 3,
            address: 'Санкт-Петербург, ул.Большая Конюшенная'
        },
        {
            id: Math.random(),
            userId: 1,
            paths: ['/images/notebooks/3/1.jpg', '/images/notebooks/3/2.png', '/images/notebooks/3/3.png'],
            description: 'Хороший товар',
            category: 'notebooks',
            screenSize: 15,
            processor: 'Intel Core i7',
            ram: 16,
            product: 'Ноутбук ASUS ROG Strix SCAR 15 G533ZX-LN087W черный',
            type: 'Игровой ноутбук',
            money: 445999,
            date: new Date('2022-03-25'),
            selected: false,
            countViews: 3,
            address: 'Санкт-Петербург, ул.Большая Конюшенная'
        },
        {
            id: Math.random(),
            userId: 1,
            paths: ['/images/notebooks/4/1.jpg', '/images/notebooks/4/2.jpg', '/images/notebooks/4/3.jpg'],
            description: 'Хороший товар',
            category: 'notebooks',
            product: 'Ультрабук HP Pavilion 15-eg0065ur серебристый',
            screenSize: 15,
            processor: 'Intel Core i3',
            ram: 8,
            money: 45000,
            type: 'Ультрабук',
            date: new Date('2022-03-25'),
            selected: false,
            countViews: 3,
            address: 'Санкт-Петербург, ул.Большая Конюшенная'
        },
        {
            id: Math.random(),
            userId: 1,
            paths: ['/images/notebooks/5/1.jpg', '/images/notebooks/5/2.jpg', '/images/notebooks/5/3.jpg'],
            description: 'Хороший товар',
            category: 'notebooks',
            product: 'Ультрабук HP Laptop 14s-fq0111ur синий',
            screenSize: 14,
            processor: 'Intel Core i3',
            ram: 8,
            type: 'Ультрабук',
            money: 37999,
            date: new Date('2022-03-25'),
            selected: false,
            countViews: 3,
            address: 'Санкт-Петербург, ул.Большая Конюшенная'
        },
    ]
};

const {cars, buildings, cameras, notebooks} = categories;
export const data = [...cars, ...buildings, ...cameras, ...notebooks];
export const users = [
    {id: 1, name: 'Дядя Вася'},
    {id: 2, name: 'Галина'}
];